---
# # win baseline 1052 state
# - name: "win_baseline_1052_state | Ensure 'Devices - Allowed to format and eject removable media' is set to 'Administrators'"
#   win_regedit:
#     path: "{{ win_baseline_1052_state_Path }}"
#     name: "{{ win_baseline_1052_state_Name }}"
#     data: "{{ win_baseline_1052_state_Data }}"
#     type: "{{ win_baseline_1052_state_Type }}"
#   when:
#     win_baseline_1052_state_Manage
# # win baseline 1149 state
# - name: "win_baseline_1149_state | Ensure 'Microsoft network client - Digitally sign communications (always)' is set to 'Enabled'"
#   win_regedit:
#     path: "{{ win_baseline_1149_state_Path }}"
#     name: "{{ win_baseline_1149_state_Name}}"
#     data: "{{ win_baseline_1149_state_Data }}"
#     type: "{{ win_baseline_1149_state_Type }}"
#   when:
#     win_baseline_1149_state_Manage
# # win baseline 1153 state
# - name: "win_baseline_1153_state | Ensure 'Network access: Do not allow anonymous enumeration of SAM accounts' is set to 'Enabled'"
#   win_regedit:
#     path: "{{ win_baseline_1153_state_Path }}"
#     name: "{{ win_baseline_1153_state_Name }}"
#     data: "{{ win_baseline_1153_state_Data }}"
#     type: "{{ win_baseline_1153_state_Type }}"
#   when:
#     win_baseline_1153_state_Manage
# # win baseline 1155 state
# - name: "win_baseline_1155_state | Ensure 'Interactive logon: Number of previous logons to cache (in case domain controller is not available)' is set to '1'"
#   win_regedit:
#     path: "{{ win_baseline_1155_state_Path }}"
#     name: "{{ win_baseline_1155_state_Name }}"
#     data: "{{ win_baseline_1155_state_Data }}"
#     type: "{{ win_baseline_1155_state_Type }}"
#   when:
#     win_baseline_1155_state_Manage
# # win_baseline 5263 state
# - name: "win_baseline_5263_state | Ensure 'No auto-restart with logged on users for scheduled automatic updates installations' is set to 'Disabled'"
#   win_regedit:
#     path: "{{ win_baseline_5263_state_Path }}"
#     name: "{{ win_baseline_5263_state_Name }}"
#     data: "{{ win_baseline_5263_state_Data }}"
#     type: "{{ win_baseline_5263_state_Type }}"
#   when:
#     win_baseline_5263_state_Manage
# # win baseline 7805 state
# - name: "win_baseline_7805_state | Ensure 'Configure Automatic Updates' is set to 'Enabled'"
#   win_regedit:
#     path: "{{ win_baseline_7805_state_Path }}"
#     name: "{{ win_baseline_7805_state_Name }}"
#     data: "{{ win_baseline_7805_state_Data }}"
#     type: "{{ win_baseline_7805_state_Type }}"
#   when:
#     win_baseline_7805_state_Manage
# # win baseline 8248 state
# - name: "win_baseline_8248_state | Ensure 'Allow Digest Authentication' is set to 'Enabled'"
#   win_regedit:
#     path: "{{ win_baseline_8248_state_Path }}"
#     name: "{{ win_baseline_8248_state_Name }}"
#     data: "{{ win_baseline_8248_state_Data }}"
#     type: "{{ win_baseline_8248_state_Type }}"
#   when:
#     win_baseline_8248_state_Manage

# -----------------------
# Windows total playbooks
# -----------------------

# error:https://stackoverflow.com/questions/66335800/error-couldnt-resolve-module-action-this-often-indicates-a-misspelling-miss
# - name: "win_baseline_1071_state | Ensure 'Minimum password length' is set to '14 or more character(s)'"
#   win_security_policy:
#     section: "{{ win_baseline_1071_state_Section }}"
#     key: "{{ win_baseline_1071_state_Key }}"
#     value: "{{ win_baseline_1071_state_Value }}"
#   when:
#     win_baseline_1071_state_Manage

# - name: "win_baseline_1072 | Ensure 'Minimum password age' is set to '1 or more day(s)'"
#   win_security_policy:
#     section: "{{win_baseline_1072_state_Section }}"
#     key: "{{ win_baseline_1072_state_Key }}"
#     value: "{{ win_baseline_1072_state_Value }}"
#   when:
#     win_baseline_1072_state_Manage

# - name: "win_baseline_1091_state | Ensure 'Interactive logon - Prompt user to change password before expiration' is set to 'between 5 and 14 days'"
#   win_regedit:
#     path: "{{ win_baseline_1091_state_Path }}"
#     name: "{{ win_baseline_1091_state_Name }}"
#     data: "{{ win_baseline_1091_state_Data }}"
#     type: "{{ win_baseline_1091_state_Type }}"
#   when:
#     win_baseline_1091_state_Manage

# error
# - name: "win_baseline_1092_state | Ensure 'Password must meet complexity requirements' is set to 'Enabled'"
#   win_security_policy:
#     section: "{{ win_baseline_1092_state_Section }}"
#     key: "{{ win_baseline_1092_state_Key }}"
#     value: "{{ win_baseline_1092_state_Value }}"

# - name: "win_baseline_1134_state | Ensure 'Logon banner title' is ser to 'This is an interest computer system of ABB Asea Brown Boveri Ltd'"
#   win_regedit:
#     path: "{{ win_baseline_1134_state_Path }}"
#     name: "{{ win_baseline_1134_state_Name }}"
#     data: "{{ win_baseline_1134_state_Data }}"
#     type: "{{ win_baseline_1134_state_Type }}"
#   when:
#     win_baseline_1134_state_Manage

# - name: "win_baseline_1156_state | Ensure 'Audit - Shut down system immediately if unable to log security audits' is set to 'Disabled'"
#   win_regedit:
#     path: "{{ win_baseline_1156_state_Path }}"
#     name: "{{ win_baseline_1156_state_Name }}"
#     data: "{{ win_baseline_1156_state_Data }}"
#     type: "{{ win_baseline_1156_state_Type }}"
#   when:
#     win_baseline_1156_state_Manage

# - name: "win_baseline_1162_state | Ensure 'Devices: Restrict floppy access to locally logged-on user only' is set to 'Enabled'"
#   win_regedit:
#     path: "{{ win_baseline_1162_state_Path }}"
#     name: "{{ win_baseline_1162_state_Name }}"
#     data: "{{ win_baseline_1162_state_Data }}"
#     type: "{{ win_baseline_1162_state_Type }}"
#   when:
#     win_baseline_1162_state_Manage

# - name: "win_baseline_1163_state | Ensure 'Devices - Prevent users from installing printer drivers' is set to 'Enabled'"
#   win_regedit:
#     path: "{{ win_baseline_1163_state_Path }}"
#     name: "{{ win_baseline_1163_state_Name }}"
#     data: "{{ win_baseline_1163_state_Data }}"
#     type: "{{ win_baseline_1163_state_Type }}"
#   when:
#     win_baseline_1163_state_Manage

# - name: "win_baseline_1164_state | Ensure 'Network security - Do not store LAN Manager hash value on next password change' is set to 'Enabled'"
#   win_regedit:
#     path: "{{ win_baseline_1164_state_Path }}"
#     name: "{{ win_baseline_1164_state_Name }}"
#     data: "{{ win_baseline_1164_state_Data }}"
#     type: "{{ win_baseline_1164_state_Type }}"
#   when:
#     win_baseline_1164_state_Manage

# - name: "win_baseline_1169_state | Ensure 'MSS - (AutoAdminLogon) Enable Automatic Logon (not recommended)' is set to 'Disabled'"
#   win_regedit:
#     path: "{{ win_baseline_1169_state_Path }}"
#     name: "{{ win_baseline_1169_state_Name }}"
#     data: "{{ win_baseline_1169_state_Data }}"
#     type:  "{{ win_baseline_1169_state_Type }}"
#   when:
#     win_baseline_1169_state_Manage

# 2.7
# - name: "win_baseline_1172_state | Ensure 'MSS - (DisableIPSourceRouting) IP source routing protection level (protects against packet spoofing)' is set"
#   win_regedit:
#     path: "{{ win_baseline_1172_state_Path }}"
#     name: "{{ win_baseline_1172_state_Name }}"
#     data: "{{ win_baseline_1172_state_Data }}"
#     type: "{{ win_baseline_1172_state_Type }}"
#   when:
#     win_baseline_1172_state_Manage

# - name: "win_baseline_1176_state | Devices: Restrict CD-ROM access to locally logged-on user only"
#   win_regedit:
#     path: "{{ win_baseline_1176_state_Path }}"
#     name: "{{ win_baseline_1176_state_Name }}"
#     data: "{{ win_baseline_1176_state_Data }}"
#     type: "{{ win_baseline_1176_state_Type }}"
#   when:
#     win_baseline_1176_state_Manage

# - name: "win_baseline_1177_state | Enure 'Enable IPSec protect Kerberos RSVP traffic' is set to 'Enabled'"
#   win_regedit:
#     path: "{{ win_baseline_1177_state_Path }}"
#     name: "{{ win_baseline_1177_state_Name }}"
#     data: "{{ win_baseline_1177_state_Data }}"
#     type: "{{ win_baseline_1177_state_Type }}"
#   when:
#     win_baseline_1177_state_Manage

# not sure
# - name: "win_baseline_1181_state | Ensure 'Simple Netowrk Management Protocol trap' service is diabled"
#   win_service:
#     name: snmptrap
#     state: stopped
#     enabled: no
#   when:
#     win_baseline_1181_state_Manage

# - name: "win_baseline_1183_state | Ensure 'Autorun for all drivers' is set to 'Disabled'"
#   win_regedit:
#     path: "{{ win_baseline_1183_state_Path }}"
#     name: "{{ win_baseline_1183_state_Name }}"
#     data: "{{ win_baseline_1183_state_Data }}"
#     type: "{{ win_baseline_1183_state_Type }}"
#   when:
#     win_baseline_1183_state_Manage

# - name: "win_baseline_1184_state | Ensure 'MSS - (PerformRouterDiscovery) Allow IRDP to detect and configure Default Gateway addresses (could lead to DoS)' is set to 'Disabled'"
#   win_regedit:
#     path: "{{ win_baseline_1184_state_Path }}"
#     name: "{{ win_baseline_1184_state_Name }}"
#     data: "{{ win_baseline_1184_state_Data }}"
#     type: "{{ win_baseline_1184_state_Type }}"
#   when:
#     win_baseline_1184_state_Manage

# - name: "win_baseline_1188_state | Ensure 'System objects - Require case insensitivity for non-Windows subsystems' is set to 'Enabled'"
#   win_regedit:
#     path: "{{ win_baseline_1188_state_Path }}"
#     name: "{{ win_baseline_1188_state_Name }}"
#     data: "{{ win_baseline_1188_state_Data }}"
#     type: "{{ win_baseline_1188_state_Type }}"
#   when:
#     win_baseline_1188_state_Manage

# - name: "win_baseline_1189_state | Ensure 'Microsoft network server - Digitally sign communications (always)' is set to 'Enabled'"
#   win_regedit:
#     path: "{{ win_baseline_1189_state_Path }}"
#     name: "{{ win_baseline_1189_state_Name }}"
#     data: "{{ win_baseline_1189_state_Data }}"
#     type: "{{ win_baseline_1189_state_Type }}"
#   when:
#     win_baseline_1189_state_Manage

# - name: "win_baseline_1190_state | Ensure 'Interactive logon - Do not display last user name' is set to 'Enabled'"
#   win_regedit:
#     path: "{{ win_baseline_1190_state_Path }}"
#     name: "{{ win_baseline_1190_state_Name }}"
#     data: "{{ win_baseline_1190_state_Data }}"
#     type: "{{ win_baseline_1190_state_Type }}"
#   when: 
#     win_baseline_1190_state_Manage

# - name: "win_baseline_1193_state | Ensure 'MSS - (EnableICMPRedirect) Allow ICMP redirects to override OSPF generated routes' is set to 'Disabled'"
#   win_regedit:
#     path: "{{ win_baseline_1193_state_Path }}"
#     name: "{{ win_baseline_1193_state_Name }}"
#     data:  "{{ win_baseline_1193_state_Data }}"
#     type: "{{ win_baseline_1193_state_Type }}"
#   when:
#     win_baseline_1193_state_Manage

# - name: "win_baseline_1195_state | Ensure 'MSS - (NoNameReleaseOnDemand) Allow the computer to ignore NetBIOS name release requests except from WINS servers' is set"
#   win_regedit:
#     path: "{{ win_baseline_1195_state_Path }}"
#     name: "{{ win_baseline_1195_state_Name }}"
#     data: "{{ win_baseline_1195_state_Data }}"
#     type: "{{ win_baseline_1195_state_Type }}"
#   when:
#     win_baseline_1195_state_Manage

# - name: "win_baseline_1196_state | Ensure 'MSS - (ScreenSaverGracePeriod) The time in seconds before the screen saver grace period expires (0 recommended)' is set to 'Enabled - 5 or fewer seconds'"
#   win_regedit:
#     path: "{{ win_baseline_1196_state_Path }}"
#     name: "{{ win_baseline_1196_state_Name }}"
#     data: "{{ win_baseline_1196_state_Data }}"
#     type: "{{ win_baseline_1196_state_Type }}"
#   when:
#     win_baseline_1196_state_Manage

# - name: "win_baseline_1197_state | Ensure 'Network access - Do not allow anonymous enumeration of SAM accounts' is set to 'Enabled'"
#   win_regedit:
#     path: "{{ win_baseline_1197_state_Path }}"
#     name: "{{ win_baseline_1197_state_Name }}"
#     data: "{{ win_baseline_1197_state_Data }}"
#     type: "{{ win_baseline_1197_state_Type }}"
#   when:
#     win_baseline_1197_state_Manage

# - name: "win_baseline_1199_state| Ensure 'Microsoft network server - Amount of idle time required before suspending session' is set to '15 or fewer, but not 0'"
#   win_regedit:
#     path: "{{ win_baseline_1199_state_Path }}"
#     name: "{{ win_baseline_1199_state_Name }}"
#     data: "{{ win_baseline_1199_state_Data }}"
#     type: "{{ win_baseline_1199_state_Type }}"
#   when:
#     win_baseline_1199_state_Manage

# not sure
# - name" "win_baseline_1200_state | Ensure 'Dynamic Controller: Resuse machine account password changes' is set to 'Disabled'"
#   win_regedit:
#     path: "{{ win_baseline_1200_state_Path }}"
#     name: "{{ win_baseline_1200_state_Name }}"
#     data: "{{ win_baseline_1200_state_Data }}"
#     type: "{{ win_baseline_1200_state_Type }}"
#   when:
#     win_baseline_1200_state_Manage

# - name: "win_baseline_1264_state | Ensure Dynamic Host Configuration Protocol Client' is set to 'Disabled'"
#   win_regedit:
#     path: "{{ win_baseline_1264_state_Path }}"
#     name: "{{ win_baseline_1264_state_Name }}"
#     data: "{{ win_baseline_1264_state_Data }}"
#     type: "{{ win_baseline_1264_state_Type }}"
#   when:
#     win_baseline_1264_state_Manage

# not sure
# - name: "win_baseline_1318_state | Ensure 'Enforce password history' is set to '24 or more password(s)'"
#   win_security_policy:
#     section: System Access
#     key: PasswordHistorySize
#     value: 24

# - name: "win_baseline_1366_state | Ensure 'Accounts - Limit local account use of blank passwords to console logon only' is set to 'Enabled'"
#   win_regedit:
#     path: "{{ win_baseline_1366_state_Path }}"
#     name: "{{ win_baseline_1366_state_Name }}"
#     data: "{{ win_baseline_1366_state_Data }}"
#     type: "{{ win_baseline_1366_state_Type }}"
#   when:
#     win_baseline_1366_state_Manage

# - name: "win_baseline_1368_state | Ensure 'Print Spooler' service is set to 'Automatic'"
#   win_regedit:
#     path: "{{ win_baseline_1368_state_Path }}"
#     name: "{{ win_baseline_1368_state_Name }}"
#     data: "{{ win_baseline_1368_state_Data }}"
#     type: "{{ win_baseline_1368_state_Type }}"
#   when:
#     win_baseline_1368_state_Manage

# - name: "win_baseline_1369_state | Ensure 'Shutdown - Allow system to be shut down without having to log on' is set to 'Disabled'"
#   win_regedit:
#     path: "{{ win_baseline_1369_state_Path }}"
#     name: "{{ win_baseline_1369_state_Name }}"
#     data: "{{ win_baseline_1369_state_Data }}"
#     type: "{{ win_baseline_1369_state_Type }}"
#   when:
#     win_baseline_1369_state_Manage

# - name: "win_baseline_1370_state | Ensure 'Domain member - Digitally encrypt or sign secure channel data (always)' is set to 'Enabled'"
#   win_regedit:
#     path: "{{ win_baseline_1370_state_Path }}"
#     name: "{{ win_baseline_1370_state_Name }}"
#     data: "{{ win_baseline_1370_state_Data }}"
#     type: "{{ win_baseline_1370_state_Type }}"
#   when:
#     win_baseline_1370_state_Manage

# - name: "win_baseline_1371_state | Ensure 'Domain member - Digitally encrypt secure channel data (when possible)' is set to 'Enabled'"
#   win_regedit:
#     path: "{{ win_baseline_1371_state_Path }}"
#     name: "{{ win_baseline_1371_state_Name }}"
#     data: "{{ win_baseline_1371_state_Data }}"
#     type: "{{ win_baseline_1371_state_Type }}"
#   when:
#     win_baseline_1371_state_Manage

# - name: "win_baseline_1372_state | Ensure 'Domain member - Digitally sign secure channel data (when possible)' is set to 'Enabled'"
#   win_regedit:
#     path: "{{ win_baseline_1372_state_Path }}"
#     name: "{{ win_baseline_1372_state_Name }}"
#     data: "{{ win_baseline_1372_state_Data }}"
#     type: "{{ win_baseline_1372_state_Type }}"
#   when:
#     win_baseline_1372_state_Manage

# - name: "win_baseline_1173_state | Ensure 'Domain member - Disable machine account password changes' is set to 'Disabled'"
#   win_regedit:
#     path: "{{ win_baseline_1173_state_Path }}"
#     name: "{{ win_baseline_1173_state_Name }}"
#     data: "{{ win_baseline_1173_state_Data }}"
#     type: "{{ win_baseline_1173_state_Type }}"
#   when:
#     win_baseline_1173_state_Manage

# - name: "win_baseline_1374_state | Ensure 'Domain member - Maximum machine account password age' is set to '30 or fewer days, but not 0'"
#   win_regedit:
#     path: "{{ win_baseline_1374_state_Path }}"
#     name: "{{ win_baseline_1374_state_Name }}"
#     data: "{{ win_baseline_1374_state_Data }}"
#     type: "{{ win_baseline_1374_state_Type }}"
#   when:
#     win_baseline_1374_state_Manage

# - name: "win_baseline_1375_state | Ensure 'Domain member - Require strong (Windows 2000 or later) session key' is set to 'Enabled'"
#   win_regedit:
#     path: "{{ win_baseline_1375_state_Path }}"
#     name: "{{ win_baseline_1375_state_Name }}"
#     data: "{{ win_baseline_1375_state_Data }}"
#     type: "{{ win_baseline_1375_state_Type }}"
#   when:
#     win_baseline_1375_state_Manage

# - name: "win_baseline_1176_state | Ensure 'Interactive logon - Do not require CTRL+ALT+DEL' is set to 'Disabled'"
#   win_regedit:
#     path: "{{ win_baseline_1176_state_Path }}"
#     name: "{{ win_baseline_1176_state_Name }}"
#     data: "{{ win_baseline_1176_state_Data }}"
#     type: "{{ win_baseline_1176_state_Type }}"
#   when:
#     win_baseline_1176_state_Manage

# - name: "win_baseline_1177_state | Ensure 'Interactive logon - Require Domain Controller Authentication to unlock workstation' is set to 'Enabled'"
#   win_regedit:
#     path: "{{ win_baseline_1177_state_Path }}"
#     name: "{{ win_baseline_1177_state_Name }}"
#     data: "{{ win_baseline_1177_state_Data }}"
#     type: "{{ win_baseline_1177_state_Type }}"
#   when:
#     win_baseline_1177_state_Manage

- name: "win_baseline_1178_state | Ensure 'Interactive logon - Smart card removal behavior' is set to 'Lock Workstation'"
  win_regedit:
    path: "{{ win_baseline_1178_state_Path }}"
    name: "{{ win_baseline_1178_state_Name }}"
    data: "{{ win_baseline_1178_state_Data }}"
    type: "{{ win_baseline_1178_state_Type }}"
  when:
    win_baseline_1178_state_Manage

- name: "win_baseline_1379_state | Ensure 'Microsoft network client - Digitally sign communications (if server agrees)' is set to 'Enabled'"
  win_regedit:
    path: "{{ win_baseline_1379_state_Path }}"
    name: "{{ win_baseline_1379_state_Name }}"
    data: "{{ win_baseline_1379_state_Data }}"
    type: "{{ win_baseline_1379_state_Type }}"
  when:
    win_baseline_1379_state_Manage

- name: "win_baseline_1380_state | Ensure 'Microsoft network client - Send unencrypted password to third-party SMB servers' is set to 'Disabled'"
  win_regedit:
    path: "{{ win_baseline_1380_state_Path }}"
    name: "{{ win_baseline_1380_state_Name }}"
    data: "{{ win_baseline_1380_state_Data }}"
    type: "{{ win_baseline_1380_state_Type }}"
  when:
    win_baseline_1380_state_Manage