---
- name: OS adaptive baseline
  hosts: 10.0.0.10
  vars:
    x: 0
  tasks:
    - name: Show facts available on the system
      ansible.builtin.debug:
        var: ansible_facts['os_family']

    - name: Show facts available on the system
      ansible.builtin.debug:
        var: ansible_facts['os_name']

    - name: Set x based on OS version
      set_fact:
      x: "{{ 19 if ansible_facts['os_name'] == 'winserver 2019' else 22 }}"

    - name: Show x
     ansible.builtin.debug:
        var: x