---
- name: OS adaptive baseline
  hosts: 10.0.0.10
  tasks:
    - name: Get OS information
      ansible.builtin.setup:
        gather_subset: all
      register: os_info

    - name: Print OS information
      debug:
        var: os_info['ansible_osversion']