---
- name: OS adaptive baseline
  hosts: 10.0.0.10
  tasks:
    - name: Show facts available on the system
      ansible.builtin.debug:
        var: ansible_facts['os_family']

    - name: Show facts available on the system
      ansible.builtin.debug:
        var: ansible_facts['os_name']

    - name: set a variable
      set_fact:
        x: 19
      when: ansible_facts['os_name'] == "Microsoft Windows Server 2019 Datacenter"

    - name: set a variable
       set_fact:
        x: 20
      when: ansible_facts['os_name'] == "Microsoft Windows Server 2022 Standard"

    - name: print the variable
      ansible.builtin.debug:
      var: x.stdout_lines