---
- name: "win_baseline_19057_state | Ensure Relax minimum password length limits is set to 'Enabled'"
  ansible.windows.win_regedit:
    path: "{{ win_baseline_19057_state_Path }}"
    name: "{{ win_baseline_19057_state_Name }}"
    data: "{{ win_baseline_19057_state_Data }}"
    type: "{{ win_baseline_19057_state_Type }}"
  when: win_baseline_19057_state_Manage

- name: "win_baseline_21377_state | Ensure Block persistence through WMI event subscription is set to block"
  ansible.windows.win_regedit:
    path: "{{ win_baseline_21377_state_Path }}"
    name: "{{ win_baseline_21377_state_Name }}"
    data: "{{ win_baseline_21377_state_Data }}"
    type: "{{ win_baseline_21377_state_Type }}"
  when: win_baseline_21377_state_Manage

- name: "win_baseline_23134_state | Ensure Do not allow location redirection is set to 'Enabled'"
  ansible.windows.win_regedit:
    path: "{{ win_baseline_23134_state_Path }}"
    name: "{{ win_baseline_23134_state_Name }}"
    data: "{{ win_baseline_23134_state_Data }}"
    type: "{{ win_baseline_23134_state_Type }}"
  when: win_baseline_23134_state_Manage